<?xml version="1.0" ?>
<!-- Copyright (c) 2025 Physical AI Course
     License: MIT
     Target: NVIDIA Jetson Orin Nano - ROS 2 Humble
-->
<robot name="humanoid_leg" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Configurable parameters for leg -->
  <xacro:arg name="leg_side" default="right"/>

  <xacro:property name="leg_side" value="$(arg leg_side)"/>

  <!-- Leg dimensions (in meters) -->
  <xacro:property name="hip_length" value="0.08"/>
  <xacro:property name="thigh_length" value="0.3"/>
  <xacro:property name="calf_length" value="0.3"/>
  <xacro:property name="foot_length" value="0.15"/>
  <xacro:property name="foot_width" value="0.08"/>

  <xacro:property name="segment_radius" value="0.02"/>

  <!-- Mass distribution -->
  <xacro:property name="hip_mass" value="0.5"/>
  <xacro:property name="thigh_mass" value="1.5"/>
  <xacro:property name="calf_mass" value="1.0"/>
  <xacro:property name="foot_mass" value="0.5"/>

  <!-- Hip (pelvis connection point) -->
  <link name="hip_${leg_side}">
    <inertial>
      <mass value="${hip_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.003"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="${segment_radius * 1.5}"/>
      </geometry>
      <material name="hip_material">
        <color rgba="0.3 0.3 0.3 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="${segment_radius * 1.5}"/>
      </geometry>
    </collision>
  </link>

  <!-- Hip-knee joint -->
  <joint name="hip_knee_${leg_side}" type="revolute">
    <parent link="hip_${leg_side}"/>
    <child link="thigh_${leg_side}"/>
    <origin xyz="0 0 -${hip_length}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.5708" upper="1.5708" effort="50" velocity="2"/>
    <dynamics damping="0.5" friction="0.0"/>
  </joint>

  <!-- Thigh -->
  <link name="thigh_${leg_side}">
    <inertial>
      <mass value="${thigh_mass}"/>
      <origin xyz="0 0 -${thigh_length/2}"/>
      <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.002"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -${thigh_length/2}"/>
      <geometry>
        <cylinder radius="${segment_radius}" length="${thigh_length}"/>
      </geometry>
      <material name="thigh_material">
        <color rgba="0.2 0.2 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 -${thigh_length/2}"/>
      <geometry>
        <cylinder radius="${segment_radius}" length="${thigh_length}"/>
      </geometry>
    </collision>
  </link>

  <!-- Knee joint -->
  <joint name="knee_ankle_${leg_side}" type="revolute">
    <parent link="thigh_${leg_side}"/>
    <child link="calf_${leg_side}"/>
    <origin xyz="0 0 -${thigh_length}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="2.5" effort="50" velocity="2"/>
    <dynamics damping="0.5" friction="0.0"/>
  </joint>

  <!-- Calf -->
  <link name="calf_${leg_side}">
    <inertial>
      <mass value="${calf_mass}"/>
      <origin xyz="0 0 -${calf_length/2}"/>
      <inertia ixx="0.015" ixy="0" ixz="0" iyy="0.015" iyz="0" izz="0.001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -${calf_length/2}"/>
      <geometry>
        <cylinder radius="${segment_radius}" length="${calf_length}"/>
      </geometry>
      <material name="calf_material">
        <color rgba="0.8 0.2 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 -${calf_length/2}"/>
      <geometry>
        <cylinder radius="${segment_radius}" length="${calf_length}"/>
      </geometry>
    </collision>
  </link>

  <!-- Ankle joint -->
  <joint name="ankle_foot_${leg_side}" type="revolute">
    <parent link="calf_${leg_side}"/>
    <child link="foot_${leg_side}"/>
    <origin xyz="0 0 -${calf_length}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-0.7854" upper="0.7854" effort="20" velocity="1"/>
    <dynamics damping="0.3" friction="0.0"/>
  </joint>

  <!-- Foot (contact with ground) -->
  <link name="foot_${leg_side}">
    <inertial>
      <mass value="${foot_mass}"/>
      <origin xyz="${foot_length/2} 0 -${foot_width/2}"/>
      <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.003"/>
    </inertial>
    <visual>
      <origin xyz="${foot_length/2} 0 -${foot_width/2}"/>
      <geometry>
        <box size="${foot_length} 0.04 ${foot_width}"/>
      </geometry>
      <material name="foot_material">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="${foot_length/2} 0 -${foot_width/2}"/>
      <geometry>
        <box size="${foot_length} 0.04 ${foot_width}"/>
      </geometry>
    </collision>
  </link>

</robot>
