<?xml version="1.0" ?>
<!-- Copyright (c) 2025 Physical AI Course
     License: MIT
     Target: NVIDIA Jetson Orin Nano - ROS 2 Humble
-->
<robot name="simple_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Define reusable properties -->
  <xacro:property name="base_mass" value="1.0"/>
  <xacro:property name="link_mass" value="0.5"/>
  <xacro:property name="ee_mass" value="0.3"/>

  <xacro:property name="base_length" value="0.1"/>
  <xacro:property name="base_width" value="0.1"/>
  <xacro:property name="base_height" value="0.1"/>

  <xacro:property name="link_length" value="0.1"/>
  <xacro:property name="link_radius" value="0.02"/>

  <xacro:property name="joint_limit_min" value="-1.5708"/>
  <xacro:property name="joint_limit_max" value="1.5708"/>
  <xacro:property name="joint_effort" value="10"/>
  <xacro:property name="joint_velocity" value="1"/>

  <!-- Base link -->
  <link name="base_link">
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${base_height/2}"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="base_material">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Macro for creating arm segments -->
  <xacro:macro name="arm_segment" params="name parent joint_name x_offset">
    <joint name="${joint_name}" type="revolute">
      <parent link="${parent}"/>
      <child link="${name}"/>
      <origin xyz="${x_offset} 0 ${link_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${joint_limit_min}" upper="${joint_limit_max}"
             effort="${joint_effort}" velocity="${joint_velocity}"/>
      <dynamics damping="0.1" friction="0.0"/>
    </joint>

    <link name="${name}">
      <inertial>
        <mass value="${link_mass}"/>
        <origin xyz="0 0 ${link_length/2}"/>
        <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.001"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${link_length/2}"/>
        <geometry>
          <cylinder radius="${link_radius}" length="${link_length}"/>
        </geometry>
        <material name="link_material">
          <color rgba="0.2 0.2 0.8 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${link_length/2}"/>
        <geometry>
          <cylinder radius="${link_radius}" length="${link_length}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- Create arm segments using macro -->
  <xacro:arm_segment name="link_1" parent="base_link"
                     joint_name="joint_1" x_offset="0"/>
  <xacro:arm_segment name="link_2" parent="link_1"
                     joint_name="joint_2" x_offset="0"/>

</robot>
